version: '3'
services:
  db:
    image: postgres:12.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always       
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    volumes:
      - odoo-web-data:/var/lib/odoo
volumes:
  odoo-web-data:
  odoo-db-data:
